stages:
  data_ingestion:
    cmd: python -m src.pipeline.data_ingestion_pipeline
    deps:
      - src/components/data_ingestion.py
      - config.yaml
    # outs:
    #   - artifacts/data_ingestion
      

  preprocessing:
    cmd: python -m src.pipeline.preprocessing_pipeline
    deps:
      - src/components/preprocessing.py
      - config.yaml
      - artifacts/data_ingestion
    outs:
      - artifacts/preprocessing
    
  feature_extraction:
    cmd: python -m src.pipeline.feature_extraction_pipeline
    deps:
      - src/components/feature_extraction.py
      - artifacts/preprocessing
    outs:
      - artifacts/features